### ISSUE TITLE
Proxy calls to replygif when Discourse uses HTTPS

### ISSUE THREAD

**Issue by gschlager** [cpradio/discourse-plugin-replygif#11]
https://meta.discourse.org/t/replygif-browsing-and-adding-reaction-gifs-easily/14936/28

**Comment by cpradio** [comment]
Can you go into more detail, would providing a SIte Setting for the URL to use to access ReplyGif solve this?

**Comment by gschlager** [comment]
Replygif currently doesn't support HTTPS. In order to prevent mixed content warnings in the browser, the client shouldn't connect to the `http://replygif.net/` endpoint directly. It would be great if the Discourse server could proxy those calls.

So, when Discourse uses HTTP it could connect to Replygif directly.
```text
Browser <== HTTP ==> http://replygif.net/...
```

But when HTTPS is used, Discourse should act as proxy for those connections.
```text
Browser <== HTTPS ==> https://discourse.example.com/replygif/... <== HTTP ==> http://replygif.net/...
```

And to answer your question: Yes, a simple site setting for the URL could work. At least it would allow the admin to configure a remote proxy for Replygif and use that URL.

**Comment by cpradio** [comment]
> And to answer your question: Yes, a simple site setting for the URL could work. At least it would allow the admin to configure a remote proxy for Replygif and use that URL.

Okay, that may be the initial way this gets implemented. Later, I think I could look into how to make that route available as part of the plugin (if possible).

**Comment by cpradio** [comment]
Added site setting as part of [d42e515dd7](https://github.com/cpradio/discourse-plugin-replygif/commit/d42e515dd752cd2148b4e651d398be2c76df7407)
![image](https://cloud.githubusercontent.com/assets/2060315/9818200/4140bca8-5875-11e5-84f6-6b0aaada3c2e.png)

**Comment by cpradio** [comment]
@gschlager If you get around to creating a Proxy and using the setting to make it work, could you submit a PR to the README.md that details step by step what needs to happen? I'd love to have that as part of the documentation.
