### ISSUE TITLE
Uncaught TypeError: Cannot read property 'inlineBetween' of undefined

### ISSUE THREAD

**Issue by wil93** [cpradio/discourse-plugin-replygif#13]
I can't see the button to add gifs, and I get this in the console:

```
_plugin-third-party-50d2bd319858511af0888741a3aa50818b679a421faef00a443f413a3b6b4542.js:5 Uncaught TypeError: Cannot read property 'inlineBetween' of undefined
    at _plugin-third-party-50d2bd319858511af0888741a3aa50818b679a421faef00a443f413a3b6b4542.js:5
    at _plugin-third-party-50d2bd319858511af0888741a3aa50818b679a421faef00a443f413a3b6b4542.js:66
(anonymous) @ _plugin-third-party-50d2bd319858511af0888741a3aa50818b679a421faef00a443f413a3b6b4542.js:5
(anonymous) @ _plugin-third-party-50d2bd319858511af0888741a3aa50818b679a421faef00a443f413a3b6b4542.js:66
```

**Comment by cpradio** [comment]
inlineBetween doesn't appear anywhere in the source code for this plugin... what version of Discourse and what version of the Plugin are you using?

Also, the plugin works just fine on my sandbox (which is up-to-date)

**Comment by wil93** [comment]
Just updated with `./launcher rebuild app`

https://forum.olinfo.it

**Comment by cpradio** [comment]
Yeah, definitely still works on my sandbox (https://sandbox.cpradio.org/).

What version of the plugin are you running, what other plugins do you have installed?

**Comment by wil93** [comment]
These are the other plugins I have:

```
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/kasperpeulen/discourse-mathjax
          - git clone https://github.com/discourse/discourse-spoiler-alert.git
          - git clone https://github.com/discourse/discourse-solved.git
          - git clone https://github.com/discourse/discourse-tagging.git
          - git clone https://github.com/cpradio/discourse-plugin-replygif.git
```

> What version of the plugin are you running

I think the git master one, I just followed the readme

**Comment by cpradio** [comment]
Your MathJax plugin is the issue, it is severely out of date.
You need to switch to the official plugin
https://meta.discourse.org/t/discourse-math-plugin/65770

**Comment by cpradio** [comment]
Also, there is an open issue on the MathJax github repo of the exact error you received
https://github.com/kasperpeulen/discourse-mathjax/issues/43

Switching to the Discourse Official plugin will definitely solve your issue.

**Comment by cpradio** [comment]
Since you use HTTPS, you need to follow this additional setup, as ReplyGIF doesn't support HTTPS (on its own)
https://github.com/cpradio/discourse-plugin-replygif#https-additional-setup

Unfortunately, that requires yet another rebuild (for the template to take effect).

**Comment by wil93** [comment]
Yes, now everything is working (except for the fact that the gif selector is quite glitchy). Thanks 😄

**Comment by cpradio** [comment]
By glitchy, you mean the GIFs keep loading pushing images around for the first few seconds? Yeah, that is expected. It should work flawlessly from here on out though.

**Comment by wil93** [comment]
Yes, also I don't really like that the gifs are still until you "select" them, they should be always moving 😄
